name: Build WEACT H750 Custom OpenMV Firmware

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04  # 안정적인 LTS 버전 사용
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git python3 python3-pip
        
    - name: Install ARM GCC (older compatible version)
      run: |
        wget -q https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/9-2020-q2-update/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
        tar -xjf gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
        sudo mv gcc-arm-none-eabi-9-2020-q2-update /opt/gcc-arm-none-eabi
        echo "/opt/gcc-arm-none-eabi/bin" >> $GITHUB_PATH
        
    - name: Verify ARM GCC installation
      run: |
        arm-none-eabi-gcc --version
        
    - name: Update git submodules
      run: |
        git submodule update --init --recursive --depth=1
        cd src/micropython
        git submodule update --init --recursive --depth=1
        
    - name: Build MicroPython cross-compiler
      run: |
        cd src/micropython/mpy-cross
        make CFLAGS_EXTRA="-Wno-error=dangling-pointer -Wno-error=enum-int-mismatch"
        
    - name: Build WEACT H750 Custom firmware
      run: |
        cd src
        make TARGET=WEACT_H750_CUSTOM CFLAGS_EXTRA="-Wno-error=dangling-pointer -Wno-error=enum-int-mismatch" -j$(nproc)
        
    - name: List generated files
      run: |
        echo "=== Build directory contents ==="
        find src/build -name "*.bin" -o -name "*.elf" -o -name "*.dfu" | head -20
        
    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v3
      with:
        name: weact-h750-custom-firmware
        path: |
          src/build/bin/*.bin
          src/build/bin/*.elf
          src/build/bin/*.dfu
        retention-days: 30
        
    - name: Create release on tag
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          src/build/bin/*.bin
          src/build/bin/*.dfu
        name: WEACT H750 Custom Firmware ${{ github.ref_name }}
        body: |
          ## WEACT H750 Custom Board Firmware
          
          **Features:**
          - STM32H750VBT6 MCU (400MHz)
          - OV7725 Camera (30m beacon detection)
          - W5500 Ethernet
          - RGB Status LEDs
          
          **Files:**
          - `firmware.bin`: Main firmware
          - `bootloader.bin`: Bootloader
          - `openmv.bin`: Complete firmware package
          
          **Upload Instructions:**
          ```bash
          dfu-util -a 0 -s 0x08000000:leave -D openmv.bin
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
